<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tetrad-configuration [
        <!ELEMENT tetrad-configuration (session-node*)>
        <!ELEMENT session-node (models, display-component, model-chooser, tooltip)>
        <!ELEMENT models (model+)>
        <!ELEMENT model (logger?, model-class, editor-class, params-class?, params-editor-class?)>
        <!ELEMENT params-editor-class (#PCDATA)>
        <!ELEMENT params-class (#PCDATA)>
        <!ELEMENT logger (event+)>
        <!ELEMENT event EMPTY>
        <!ELEMENT model-class (#PCDATA)>
        <!ELEMENT editor-class (#PCDATA)>
        <!ELEMENT display-component (#PCDATA)>
        <!ELEMENT model-chooser (#PCDATA)>
        <!ELEMENT tooltip (#PCDATA)>

        <!ATTLIST event id NMTOKENS #REQUIRED description CDATA #REQUIRED default (on|off) #IMPLIED>
        <!ATTLIST display-component image NMTOKENS #IMPLIED>
        <!ATTLIST model-chooser title NMTOKENS #REQUIRED>
        <!ATTLIST session-node id ID #REQUIRED>
        <!ATTLIST model name NMTOKENS #REQUIRED acronym NMTOKENS #REQUIRED help NMTOKENS #REQUIRED category NMTOKENS #IMPLIED>
        ]>
<tetrad-configuration>
    <session-node id="Graph">
        <models>
            <model name="Directed Acyclic Graph" acronym="DAG" help="dag">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.DagWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.DagEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.GraphParams</params-class>
                <params-editor-class>edu.cmu.tetradapp.editor.GraphParamsEditor
                </params-editor-class>
            </model>
            <model name="Structural Equation Model Graph" acronym="SEM Graph"
                   help="sem_graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.SemGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.SemGraphEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.CyclicGraphParams</params-class>
                <params-editor-class>edu.cmu.tetradapp.editor.GraphParamsEditor
                </params-editor-class>
            </model>
            <model name="General Graph" acronym="Graph" help="general_graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GraphWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.CyclicGraphParams</params-class>
                <params-editor-class>edu.cmu.tetradapp.editor.GraphParamsEditor
                </params-editor-class>
            </model>
            <model name="Time Lag Graph" acronym="Lag Graph" help="time_lag_graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.TimeLagGraphWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.TimeLagGraphEditor
                </editor-class>
            </model>
        </models>
        <display-component image="graphIcon.gif"/>
        <model-chooser title="Graph Types"/>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Node:
                 <br> (1) No inputs OR
                 <br> (2) Data (to extract variables)
                 <br><i> Also (to extract a graph) any of these:
                 <br>Search, PM, IM, Estimator, Updator</i>
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="GraphManip">
        <models>
            <model name="Choose Dag in Pattern" acronym="Dag in Pattern"
                   help="graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.DagInPatternWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor</editor-class>
            </model>
            <model name="Show DAGs in Pattern" acronym="Dags in Pattern"
                   help="graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="selected_graph" description="Selected Graph" default="on"/>
                    <event id="all_graphs" description="All Graphs"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.ScoredGraphsWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.ScoredGraphsDisplay</editor-class>
            </model>
            <model name="Generate Pattern from Dag" acronym="Pattern from Dag"
                   help="graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pattern" description="Pattern" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.PatternFromDagGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Generate PAG from Dag" acronym="PAG from Dag"
                   help="graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pag" description="PAG" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.PagFromDagGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Make Bidirected Edges Undirected" acronym="Make bidirected undirected"
                   help="graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BidirectedToUndirectedWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Make Undirected Edges Bidirected" acronym="Make undirected bidirected"
                   help="graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.UndirectedToBidirectedWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Make All Edges Undirected" acronym="Make all edges undirected"
                   help="graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.AllEdgesUndirectedWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Generate Complete Graph" acronym="Generate complete graph"
                   help="graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GenerateCompleteGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Extract Markov Blanket" acronym="MB from Graph"
                   help="graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.ExtractMarkovBlanketWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Extract Structure Model" acronym="Extract Struct Model"
                   help="graph">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.ExtractStructureModelWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Graph Selections" acronym="Graph Select"
                   help="graph_selections">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="result" description="Result" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GraphSelectionWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphSelectionEditor
                </editor-class>
            </model>
        </models>
        <display-component image="graphIcon.gif"/>
        <model-chooser title="Graph Manipulations"/>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Node:
                 <br> (1) Search OR
                 <br> (2) Graph
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="PM">
        <models>
            <model name="Bayes Parametric Model" acronym="Bayes PM"
                   help="bayes_pm">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pm" description="Parametric Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BayesPmWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.BayesPmEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.BayesPmParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesPmParamsEditor
                </params-editor-class>
            </model>
            <model name="SEM Parametric Model" acronym="SEM PM" help="sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pm" description="Parametric Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.SemPmWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.SemPmEditor
                </editor-class>
            </model>
            <model name="Generalized SEM Parametric Model" acronym="Gen. SEM PM" help="sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pm" description="Parametric Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GeneralizedSemPmWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.GeneralizedSemPmEditor
                </editor-class>
            </model>
        </models>
        <display-component image="pmIcon.gif"/>
        <model-chooser title="Types of Parameterized Models"/>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Node:
                 <br> (1) Graph, OR
                 <br> (2) Graph AND Data (to extract discrete categories)
                 <br><i> Also (to extract a PM) any of these:
                 <br>IM, Estimator</i>
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="IM">
        <models>
            <model name="Bayes Instantiated Model" acronym="Bayes IM"
                   help="bayes_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BayesImWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.BayesImEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.BayesImParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesImParamsEditor
                </params-editor-class>
            </model>
            <model name="Bayes Instantiated Model: Observed Variables Only"
                   acronym="Bayes IM Obs"
                   help="bayes_im_obs">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BayesImWrapperObs
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.BayesImEditorObs
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.BayesImParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesImParamsEditor
                </params-editor-class>
            </model>
            <model name="Dirichlet Bayes Instantiated Model"
                   acronym="Dir Bayes IM" help="dirichlet_bayes_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.DirichletBayesImWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DirichletBayesImEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.DirichletBayesImParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.DirichletBayesImParamsEditor
                </params-editor-class>
            </model>
            <model name="SEM Instantiated Model" acronym="SEM IM" help="sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.SemImWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.SemImEditor
                </editor-class>
                <params-class>edu.cmu.tetradapp.model.SemImParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.SemImParamsEditor
                </params-editor-class>
            </model>
            <model name="Standardized SEM Instantiated Model" acronym="St SEM IM" help="sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.StandardizedSemImWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.StandardizedSemImEditor</editor-class>
            </model>
            <model name="Generalized SEM Instantiated Model" acronym="Gen. SEM IM" help="gen_sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GeneralizedSemImWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.GeneralizedSemImEditor</editor-class>
            </model>
        </models>
        <display-component image="imIcon.gif"/>
        <model-chooser title="Types of Instantiated Models"/>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Node:
                 <br> (1) PM (Bayes or SEM), OR
                 <br> (2) IM (to convert Dirichlet Bayes IM to Bayes IM), OR
                 <br> (3) Estimator (to extract IM)
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="Data">
        <models>
            <model name="Data Wrapper" acronym="Data" help="data">
                <model-class>edu.cmu.tetradapp.model.DataWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.DataParams</params-class>
            </model>
            <model name="Bayes IM Simulated Data" acronym="Bayes Data"
                   help="data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BayesDataWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.BayesDataParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesDataParamsEditor
                </params-editor-class>
            </model>
            <model name="Dirichlet Bayes IM Simulated Data"
                   acronym="Dir Bayes Data" help="data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.DirichletBayesDataWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.BayesDataParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesDataParamsEditor
                </params-editor-class>
            </model>
            <model name="SEM IM Simulated Data" acronym="SEM Data" help="data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.SemDataWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.SemDataParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.SemDataParamsEditor
                </params-editor-class>
            </model>
            <model name="Implied Covariance Matrix--Measured" acronym="Implied Covar Meas" help="data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.ImpliedCovarianceDataWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.SemDataParams
                </params-class>
            </model>
            <model name="Implied Covariance Matrix--All" acronym="Implied Covar All" help="data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.ImpliedCovarianceDataAllWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.SemDataParams
                </params-class>
            </model>
            <model name="Generalized SEM IM Simulated Data" acronym="Gen. SEM Data" help="data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GeneralizedSemDataWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>edu.cmu.tetradapp.model.SemDataParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.SemDataParamsEditor
                </params-editor-class>
            </model>
        </models>
        <display-component image="dataIcon.gif"/>
        <model-chooser title="Types of data Objects"/>
        <tooltip>
            <![CDATA[
               <html> Allowable Input Node:
                 <br> (1) No inputs (standalone data set), OR
                 <br> (2) IM (Bayes or SEM, to simulate data)
               </html>
            ]]>
        </tooltip>
    </session-node>
    <session-node id="DataManip">
        <models>
            <model name="Discretize Dataset" acronym="Discretize" help="data"
                   category="General">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.DiscretizationWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>
                    edu.cmu.tetradapp.model.datamanip.DiscretizationParams
                </params-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.datamanip.DiscretizationParamsEditor
                </params-editor-class>
            </model>
            <model name="Convert Numerical Discrete To Continuous" acronym="Continuize" help="convertdiscrete"
                   category="General">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.ConvertNumericalDiscreteToContinuousWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Expand Case Multipliers" acronym="Expand" help="data"
                   category="General">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.ExpandCaseMultipliersWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Calculator" acronym="Calculator" help="data"
                   category="General">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.CalculatorWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>
                    edu.cmu.tetrad.calculator.CalculatorParams
                </params-class>
                <params-editor-class>edu.cmu.tetradapp.editor.CalculatorEditor
                </params-editor-class>
            </model>
            <model name="Copy Selected Dataset" acronym="Copy Selected"
                   help="copyselecteddata" category="General">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.CopySelectedDatasetWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Copy All Datasets" acronym="Copy All"
                   help="copyselecteddata" category="General">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.CopyAllDatasetsWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Merge Datasets" acronym="Merge Datasets"
                   help="mergedatasets" category="General">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.MergeDatasetsWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Shift Data" acronym="Shift Data" help="data"
                   category="General">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.ShiftDataWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-class>
                    edu.cmu.tetradapp.model.datamanip.ShiftDataParams
                </params-class>
                <params-editor-class>edu.cmu.tetradapp.editor.datamanip.ShiftDataParamsEditor
                </params-editor-class>
            </model>
            <model name="Convert to Correlation Matrix" acronym="Corr Matrix"
                   help="corr" category="Convert">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.CorrMatrixConverter
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Convert to Covariance Matrix" acronym="Cov Matrix"
                   help="covariances" category="Convert">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.datamanip.CovMatrixWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Difference of Covariance Matrices" acronym="Cov Matrix Diff"
                   help="covdiff" category="Convert">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.datamanip.CovMatrixDifferenceWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Sum of Covariance Matrices" acronym="Cov Matrix Sum"
                   help="covsum" category="Convert">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>