<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tetrad-configuration [
        <!ELEMENT tetrad-configuration (session-node*)>
        <!ELEMENT session-node (models, display-component, model-chooser, node-specific-message)>
        <!ELEMENT models (model+)>
        <!ELEMENT model (logger?, model-class, editor-class, params-editor-class?)>
        <!ELEMENT params-editor-class (#PCDATA)>
        <!ELEMENT logger (event+)>
        <!ELEMENT event EMPTY>
        <!ELEMENT model-class (#PCDATA)>
        <!ELEMENT editor-class (#PCDATA)>
        <!ELEMENT display-component (#PCDATA)>
        <!ELEMENT model-chooser (#PCDATA)>
        <!ELEMENT node-specific-message (#PCDATA)>

        <!ATTLIST event id NMTOKENS #REQUIRED description CDATA #REQUIRED default (on|off) #IMPLIED>
        <!ATTLIST display-component image NMTOKENS #IMPLIED>
        <!ATTLIST model-chooser title NMTOKENS #REQUIRED>
        <!ATTLIST session-node id ID #REQUIRED>
        <!ATTLIST model name NMTOKENS #REQUIRED acronym NMTOKENS #REQUIRED help NMTOKENS #REQUIRED category NMTOKENS #IMPLIED>
        ]>
<tetrad-configuration>
    <session-node id="Graph">
        <models>
            <model name="Graph" acronym="Graph" help="general_graph" category="Basic Graph Types">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GraphWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Directed Acyclic Graph" acronym="DAG" help="dag" category="Basic Graph Types">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.DagWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.DagEditor</editor-class>
            </model>
            <model name="Structural Equation Model Graph" acronym="SEM Graph"
                   help="sem_graph" category="Basic Graph Types">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.SemGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.SemGraphEditor
                </editor-class>
            </model>
            <model name="Time Lag Graph" acronym="Lag Graph" help="time_lag_graph" category="Basic Graph Types">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.TimeLagGraphWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.TimeLagGraphEditor
                </editor-class>
            </model>

            <!--Graph manip-->
            <model name="Display Subgraphs" acronym="Graph Select"
                   help="graph_selections" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="result" description="Result" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GraphSelectionWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphSelectionEditor
                </editor-class>
            </model>
            <model name="Choose Dag in Pattern" acronym="Dag in Pattern"
                   help="graph" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.DagInPatternWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor</editor-class>
            </model>
            <model name="Choose Mag in PAG" acronym="Mag in PAG"
                   help="graph" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.MagInPagWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor</editor-class>
            </model>
            <model name="Show DAGs in Pattern" acronym="Dags in Pattern"
                   help="graph" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="selected_graph" description="Selected Graph" default="on"/>
                    <event id="all_graphs" description="All Graphs"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.ScoredGraphsWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.ScoredGraphsDisplay</editor-class>
            </model>
            <model name="Generate Pattern from Dag" acronym="Pattern from Dag"
                   help="graph" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pattern" description="Pattern" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.PatternFromDagGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Generate PAG from Dag" acronym="PAG from Dag"
                   help="graph" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pag" description="PAG" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.PagFromDagGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Generate PAG from tsDag" acronym="PAG from tsDag"
                   help="graph" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pag" description="PAG" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.TsPagFromDagGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Make Bidirected Edges Undirected" acronym="Make bidirected undirected"
                   help="graph" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BidirectedToUndirectedWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Make Undirected Edges Bidirected" acronym="Make undirected bidirected"
                   help="graph" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.UndirectedToBidirectedWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Make All Edges Undirected" acronym="Make all edges undirected"
                   help="graph" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.AllEdgesUndirectedWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Generate Complete Graph" acronym="Generate complete graph"
                   help="graph" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GenerateCompleteGraphWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
            <model name="Extract Structure Model" acronym="Extract Struct Model"
                   help="graph" category="Graph Manipulations">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="graph" description="Graph" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.ExtractStructureModelWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.GraphEditor
                </editor-class>
            </model>
        </models>
        <display-component image="graphIcon.gif"/>
        <model-chooser title="Graphs and Graph Manipulations">
            edu.cmu.tetradapp.app.CategorizingModelChooser
        </model-chooser>
        <!--<model-chooser title="Graph Types"/>-->
        <node-specific-message>
            <![CDATA[
               <html> Sorry, this box certain inputs; please see the manual. Possible inputs are:
                 <br> (1) No inputs
                 <br> (2) Data (to extract variables)
                 <br> (3) Also (to extract a graph) any of these: Search, PM, IM, Estimator, Updator
                 <br> Note that for the parent boxes, models need to have been created.
               </html>
            ]]>
        </node-specific-message>
    </session-node>
    <session-node id="PM">
        <models>
            <model name="Bayes Parametric Model" acronym="Bayes PM" help="bayes_pm">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pm" description="Parametric Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BayesPmWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.BayesPmEditor
                </editor-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesPmParamsEditor
                </params-editor-class>
            </model>
            <model name="SEM Parametric Model" acronym="SEM PM" help="sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pm" description="Parametric Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.SemPmWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.SemPmEditor
                </editor-class>
            </model>
            <model name="Generalized SEM Parametric Model" acronym="Gen. SEM PM" help="sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="pm" description="Parametric Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GeneralizedSemPmWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.GeneralizedSemPmEditor
                </editor-class>
            </model>
        </models>
        <display-component image="pmIcon.gif"/>
        <model-chooser title="Types of Parameterized Models"/>
        <node-specific-message>
            <![CDATA[
               <html> Sorry, this box certain inputs; please see the manual. Possible inputs are:
                 <br> (1) Graph, OR
                 <br> (2) Graph AND Data (to extract discrete categories)
                 <br> (3) Also (to extract a PM) any of these: IM, Estimator
                 <br> Note that for the parent boxes, models need to have been created.
               </html>
            ]]>
        </node-specific-message>
    </session-node>
    <session-node id="IM">
        <models>
            <model name="Bayes Instantiated Model" acronym="Bayes IM"
                   help="bayes_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BayesImWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.BayesImEditor
                </editor-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesImParamsEditor
                </params-editor-class>
            </model>
            <model name="Bayes Instantiated Model: Observed Variables Only"
                   acronym="Bayes IM Obs"
                   help="bayes_im_obs">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.BayesImWrapperObs
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.BayesImEditorObs
                </editor-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.BayesImParamsEditor
                </params-editor-class>
            </model>
            <model name="Dirichlet Bayes Instantiated Model"
                   acronym="Dir Bayes IM" help="dirichlet_bayes_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.DirichletBayesImWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DirichletBayesImEditor
                </editor-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.DirichletBayesImParamsEditor
                </params-editor-class>
            </model>
            <model name="SEM Instantiated Model" acronym="SEM IM" help="sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.SemImWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.SemImEditor
                </editor-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.SemImParamsEditor
                </params-editor-class>
            </model>
            <model name="Standardized SEM Instantiated Model" acronym="St SEM IM" help="sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.StandardizedSemImWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.StandardizedSemImEditor</editor-class>
            </model>
            <model name="Generalized SEM Instantiated Model" acronym="Gen. SEM IM" help="gen_sem_im">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="im" description="Instantiated Model" default="on"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.GeneralizedSemImWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.GeneralizedSemImEditor</editor-class>
            </model>
        </models>
        <display-component image="imIcon.gif"/>
        <model-chooser title="Types of Instantiated Models"/>
        <node-specific-message>
            <![CDATA[
               <html> Sorry, this box certain inputs; please see the manual. Possible inputs are:
                 <br> (1) PM (Bayes or SEM), OR
                 <br> (2) IM (to convert Dirichlet Bayes IM to Bayes IM), OR
                 <br> (3) Estimator (to extract IM)
                 <br> Note that for the parent boxes, models need to have been created.
               </html>
            ]]>
        </node-specific-message>
    </session-node>
    <session-node id="Data">
        <models>
            <model name="Data" acronym="Data" help="data" category="Data">
                <model-class>edu.cmu.tetradapp.model.DataWrapper</model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Discretize Dataset" acronym="Discretize" help="data"
                   category="Manipulation of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.DiscretizationWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.datamanip.DiscretizationParamsEditor
                </params-editor-class>
            </model>
            <model name="Convert Numerical Discrete To Continuous" acronym="Continuize" help="convertdiscrete"
                   category="Manipulation of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.datamanip.ConvertNumericalDiscreteToContinuousWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <!--<model name="Expand Case Multipliers" acronym="Expand" help="data"-->
            <!--category="Manipulation of Data">-->
            <!--<logger>-->
            <!--<event id="info" description="Information" default="on"/>-->
            <!--<event id="data" description="Data"/>-->
            <!--</logger>-->
            <!--<model-class>-->
            <!--edu.cmu.tetradapp.model.datamanip.ExpandCaseMultipliersWrapper-->
            <!--</model-class>-->
            <!--<editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>-->
            <!--</model>-->
            <model name="Calculator" acronym="Calculator" help="data"
                   category="Manipulation of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.CalculatorWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-editor-class>edu.cmu.tetradapp.editor.CalculatorEditor
                </params-editor-class>
            </model>
            <!--<model-class>-->
            <!--edu.cmu.tetradapp.model.datamanip.CopySelectedDatasetWrapper-->
            <!--</model-class>-->
            <!--<editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>-->
            <!--</model>-->
            <!--<model name="Copy All Datasets" acronym="Copy All"-->
            <!--help="copyselecteddata" category="Manipulation of Data">-->
            <!--<logger>-->
            <!--<event id="info" description="Information" default="on"/>-->
            <!--<event id="data" description="Data"/>-->
            <!--</logger>-->
            <!--<model-class>-->
            <!--edu.cmu.tetradapp.model.datamanip.CopyAllDatasetsWrapper-->
            <!--</model-class>-->
            <!--<editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>-->
            <!--</model>-->
            <model name="Collect Data Sets In One Box" acronym="Collect Data Sets In One Box"
                   help="mergedatasets" category="Manipulation of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>
                    edu.cmu.tetradapp.model.MergeDatasetsWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <!--<model name="Shift Data" acronym="Shift Data" help="data"-->
            <!--category="Manipulation of Data">-->
            <!--<logger>-->
            <!--<event id="info" description="Information" default="on"/>-->
            <!--<event id="data" description="Data"/>-->
            <!--</logger>-->
            <!--<model-class>-->
            <!--edu.cmu.tetradapp.model.datamanip.ShiftDataWrapper-->
            <!--</model-class>-->
            <!--<editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>-->
            <!--<params-editor-class>edu.cmu.tetradapp.editor.datamanip.ShiftDataParamsEditor-->
            <!--</params-editor-class>-->
            <!--</model>-->
            <model name="Convert to Correlation Matrix" acronym="Corr Matrix"
                   help="corr" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.CorrMatrixConverter
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Convert to Covariance Matrix" acronym="Cov Matrix"
                   help="covariances" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.datamanip.CovMatrixWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Inverse Matrix" acronym="Cov Matrix"
                   help="covariances" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.datamanip.InverseMatrixWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Simulate Tabular From Covariance" acronym="SimFromCov"
                   help="simfromcov" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.datamanip.SimulateFromCovWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Difference of Covariance Matrices" acronym="Cov Matrix Diff"
                   help="covdiff" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.datamanip.CovMatrixDifferenceWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Sum of Covariance Matrices" acronym="Cov Matrix Sum"
                   help="covsum" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.datamanip.CovMatrixSumWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Average of Covariance Matrices" acronym="Cov Matrix Average"
                   help="covavg" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.datamanip.CovMatrixAverageWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Convert to Time Lag Data" acronym="Time Lag"
                   help="data" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.datamanip.TimeSeriesWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.datamanip.TimeSeriesParamsEditor
                </params-editor-class>
            </model>
            <model name="Add an index predictor" acronym="Add Index"
                   help="data" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.datamanip.TimeSeriesWrapper2
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <!--<params-editor-class>-->
                <!--edu.cmu.tetradapp.editor.datamanip.TimeSeriesParamsEditor-->
                <!--</params-editor-class>-->
            </model>
            <model name="Convert to AR residuals" acronym="AR Residuals"
                   help="data" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.datamanip.ArResidualsWrapper
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-editor-class>
                    edu.cmu.tetradapp.editor.datamanip.ArResidualsParamsEditor
                </params-editor-class>
            </model>
            <model name="Whiten" acronym="Whiten"
                   help="corr" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.Whitener
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
            </model>
            <model name="Logarithmic Transform" acronym="Log"
                   help="data" category="Conversion of Data">
                <logger>
                    <event id="info" description="Information" default="on"/>
                    <event id="data" description="Data"/>
                </logger>
                <model-class>edu.cmu.tetradapp.model.LogData
                </model-class>
                <editor-class>edu.cmu.tetradapp.editor.DataEditor</editor-class>
                <params-editor-class>edu.cmu.tetradapp.editor.LogParamsEditor</params-editor-class>
            </model>
            <model name="Nonparanormal Transform" acronym="NonPN"